# Spring Boot configuration
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: jdbc:postgresql://localhost:32768/postgres
    username: postgres
    password: aniyar
  data:
    mongodb:
      uri: "mongodb+srv://aniyar:mongo@cluster0.62vhyp6.mongodb.net/jobs"
      database: jobs
      username: aniyar
      password: mongo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      default_schema: ${DEFAULT_SCHEMA:public}
      dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  logging:
    level:
      org.springframework.data.jpa: DEBUG

